"""Core interfaces."""

# ruff: noqa: D101, D102

from typing import Optional, Protocol

from httpx import Response

from wse.core.navigation.routes import Route


class IAuthService(Protocol):
    async def authenticate(self, username: str, password: str) -> None: ...
    async def is_authenticated(self) -> bool: ...


class IAuthAPI(Protocol):
    async def authenticate(self, username: str, password: str) -> str: ...
    async def validate_token(self, token: str) -> bool: ...


class IApiClient(Protocol):
    async def get(self, endpoint: str, **kwargs: object) -> Response: ...
    async def post(self, endpoint: str, **kwargs: object) -> Response: ...
    async def put(self, endpoint: str, **kwargs: object) -> Response: ...
    async def patch(self, endpoint: str, **kwargs: object) -> Response: ...
    async def delete(self, endpoint: str, **kwargs: object) -> Response: ...


class ITokenStorage(Protocol):
    def save_token(self, token: str) -> None: ...
    def load_token(self) -> Optional[str]: ...


class INavigator(Protocol):
    def navigate(self, route: Route) -> None: ...
