exclude = [
    ".github/*",
    ".idea/*",
    ".venv*",
    "docs",
    "*/conftest.py",
]
line-length = 79

[lint]
select = [
    "F",    # pyflakes: https://pypi.org/project/pyflakes/
    "E",    # pycodestyle: Error; pycodestyle: https://pypi.org/project/pycodestyle/
    "W",    # pycodestyle: Warning
    "I",    # isort: https://pypi.org/project/isort/
    "N",    # pep8-naming: https://pypi.org/project/pep8-naming/
    "D",    # pydocstyle: https://pypi.org/project/pydocstyle/
    "B",    # flake8-bugbear: https://pypi.org/project/flake8-bugbear/
    "C90",  # mccabe: https://pypi.org/project/mccabe/
    "ANN",  # flake8-annotations: https://pypi.org/project/flake8-annotations/
]
ignore = [
    "D203",     # 1 blank line required before class docstring
    "D211",     # No blank lines allowed before class docstring
    "D213",     # Multi-line docstring summary should start at the second line
    "D416",     # Section name should end with a colon
]
preview = true

[lint.pycodestyle]
max-doc-length = 72

[lint.flake8-quotes]
inline-quotes = "single"

[format]
quote-style = "single"