name: "Sphinx: Render docs"

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.4"
          cache: true
          virtualenvs-in-project: true

      - name: Check Poetry version
        run: poetry --version

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            .venv
            **/__pypackages__
          key: poetry-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry install --no-interaction --with docs, dev
          pip install toga

      - name: Build HTML
        working-directory: ./docs
        run: make html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
          force_orphan: true
          allow_empty_commit: true
