name: Test Suite

on:
  push:
    paths: [ "src/**", "tests/**", "requirements*.txt" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2-dev \
            libgirepository1.0-dev \
            pkg-config \
            python3-dev \
            gir1.2-gtk-3.0 \
            libgtk-3-dev \
            xvfb \
            build-essential \
            libssl-dev \
            libffi-dev \
            cargo \
            gobject-introspection \
            libglib2.0-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pycairo --no-binary :all:
          pip install -r requirements-dev.txt
          pip install toga[gtk]

      - name: Run tests
        env:
          STORAGE_ENCRYPTION_KEY: ${{ secrets.STORAGE_ENCRYPTION_KEY }}
        run: |
          pytest -v tests/