name: "Pytest"

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            build-essential \
            pkg-config \
            python3-dev \
            python3-venv \
            libgirepository1.0-dev \
            libcairo2-dev \
            xvfb \
            gir1.2-gtk-3.0 \
            libcanberra-gtk3-module

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install project dependencies
        run: poetry install

      - name: Install briefcase dependencies
        run: |
          echo "TOGA_BACKEND=toga_dummy" >> $GITHUB_ENV
          briefcase dev --no-run

      - name: Run tests with coverage
        run: |
          pip install toga[gtk]
          briefcase dev --test -- \
            --cov=src \
            --cov-report=term \
            --cov-report=xml:coverage.xml \
            --cov-report=html:htmlcov

      - uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: reports/lcov.info